
services:
  api:
    build: .
    container_name: whoslive-api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:6
    container_name: whoslive-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: whoslive-redis
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  mongo_data:
